[package]
name = "pilhome-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Server —— 负责管理网页和内核桥接的服务"

[dependencies]
pilhome-core = { path = "../Core" }
pilhome-netlinker = { path = "../PlugsCores/NetLinker" }
pilhome-netscanear = { path = "../PlugsCores/NetScanear" }
pilhome-sideagent = { path = "../PlugsCores/SideAgent" }
pilhome-handmodel = { path = "../PlugsCores/HandModel" }
pilhome-vescaner = { path = "../PlugsCores/VEScaner" }
pilhome-yololookup = { path = "../PlugsCores/YololookUP" }
pilhome-selflookup = { path = "../PlugsCores/SelflookUP" }
pilhome-atogrowup = { path = "../PlugsCores/ATOGrowUP" }
pilhome-autotime = { path = "../PlugsCores/AUTOTIME" }
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
serde.workspace = true
serde_json.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rumqttc = "0.24"
chrono = { version = "0.4", features = ["serde"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }
toml = "0.8"
tokio-tungstenite = "0.24"
futures-util = "0.3"
getrandom = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }
zip = "2"
mysql = "25"
ureq = { version = "2", features = ["json"] }
rquickjs = "0.9"